### PR TITLE
Upgrade to Bootstrap 3.3.5

### PR DESCRIPTION
**Pull request by kierendavies**

### CODE REVIEW

**Comment by kevinetienne** [comment]
Thanks for your contribution, happy to merge it and to release a new version but I'm not maintaining it anymore. If you want you can release a new package and I can add a notice to redirect to your repo/package.

**Comment by kierendavies** [comment]
I don't have much interest in taking over maintenance - I just wanted this particular update.  I'd appreciate it if you would merge and release a new version.

**Comment by kevinetienne** [comment]
Cool thank you for your answer I'll do a release in a couple of hours

**Comment by kevinetienne** [comment]
Updated under `1.0.0`

**Comment by kierendavies** [comment]
```
$ pip install --ignore-installed django-bootstrap-sass==1.0.0                                                      
Collecting django-bootstrap-sass==1.0.0
  Could not find a version that satisfies the requirement django-bootstrap-sass==1.0.0 (from versions: 0.0.1a0, 0.0.3a0, 0.0.4a0, 0.0.5a0, 0.0.6a0)
No matching distribution found for django-bootstrap-sass==1.0.0
```

I think you may have forgotten to upload the new packaged version.

**Comment by kevinetienne** [comment]
Sounds like I had a problem with my package data, I will have a look and let you know

**Comment by kierendavies** [comment]
```
$ pip install --ignore-installed django-bootstrap-sass==1.0.0
...
error: can't copy 'bootstrap_sass/static/fonts': doesn't exist or not a regular file
```

Do you know what's causing this?  I suspect `package_data` in `setup.py` needs to include `'static/fonts/*'`.

Thanks for the patience :)

**Comment by kevinetienne** [comment]
That's exactly the error I had when I try to run the build again today. I think I might switch to use a `MANIFEST.in` file and do a `recursive-include`

**Comment by kierendavies** [comment]
I have a fix:

``` python
package_data={'bootstrap_sass': [
    'static/*.scss',
    'static/*.js'
]
```

**Comment by kevinetienne** [comment]
Oops sorry totally forgot about the project, I think we need to include the fonts as well

**Comment by kierendavies** [comment]
Of course, my mistake

**Comment by kevinetienne** [comment]
No worries we're on the right track

**Pull request merged**
